version: '3.9'

services:
  analytics-service:
    build: .
    container_name: analytics-service
    restart: on-failure
    networks:
      - mahi
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SERVER_PORT: 4002
    ports:
      - "4002:4002"
networks:
  mahi:
    external: true