version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: patient-service-db
    restart: always
    networks:
      - mahi
    environment:
      POSTGRES_DB: patientdb
      POSTGRES_USER: patientuser
      POSTGRES_PASSWORD: patientpass
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data   # Host directory sync
networks:
  mahi:
    external: true