version: '3.9'

services:
  billing-service:
    build: .
    container_name: billing-service
    restart: on-failure
    networks:
      - mahi
    environment:
      SERVER_PORT: 4001
    ports:
      - "4001:4001"
      - "9001:9001"
networks:
  mahi:
    external: true